apiVersion: v1
kind: Service
metadata:
  name: webapp2
  labels:
    app: webapp2
spec:
  type: LoadBalancer
  ports:
   - targetPort: 9000   # Port inside the cluster
     port: 9000
     nodePort: 30080  # Port exposed to the outside
  selector:
    app: webapp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
  labels:
    app: webapp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp2
        image: docker.io/jooh777/webapp-project2:0.1
        ports:
        - containerPort: 9000
        env:
        - name: MYSQL_DATABASE
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
