apiVersion: v1
kind: Service
metadata:
  name: webapp1
  labels:
    app: webapp1
spec:
  type: LoadBalancer
  ports:
   - targetPort: 8000   # Port inside the cluster
     port: 8000
     nodePort: 30090  # Port exposed to the outside
  selector:
    app: webapp1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: webapp1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
    metadata:
      labels:
        app: webapp1
    spec:
      containers:
      - name: webapp1
        image: docker.io/jooh777/testimage:0.1
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DATABASE
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
