apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  #type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    #nodePort: 31000
  selector:
    app: mysqldb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  labels:
    app: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysqldb
        image: docker.io/jooh777/mysql:0.1
        env:
        - name: MYSQL_DATABASE
          value: "mysql"
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
